sudo: required

services:
  -docker

before_install:
   - docker build -t piuszak/devops/frontend -f frontend/Dockerfile.dev frontend/.

script:
  - docker run -e CI=true piuszak/devops/frontend yarn test