version: '3.7'

services:

  my-postgres-server:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: labDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD=${PGPASSWORD}

  my-redis-server:
    image: 'redis:latest'

  my-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
    - /opt/app/node_modules
    - ./backend:/opt/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGDATEBASE=${PGDATEBASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGPORT=${PGPORT}
    ports:
      - "5000:5000"
    depends_on:
      - my-postgres-server
      - my-redis-server

  my-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /opt/app/node_modules
      - ./frontend:/opt/app
    tty: true

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'