apiVersion: v1

kind: Service

metadata:
    name: redis-service
#    labels:
#        app: myapp
#        type: frontend

spec:
    type: ClusterIP
    ports:
        - targetPort: 6379
          port: 6379

    selector:
        app: my-redis
        type: cache
#        matchLabels:
#            type: frontend
