apiVersion: v1

kind: Service

metadata:
    name: mybackend-service
#    labels:
#        app: myapp
#        type: frontend

spec:
    type: NodePort
    ports:
        - targetPort: 5000
          port: 5000
          nodePort: 30009
#    template:
#        metadata:
#            name: myapp-pod
#            labels:
#                app: myapp
#                type: frontend
#        spec:
#            containers:
#                - name: my-nginx-container
#                  image: nginx
#    replicas: 3
    selector:
        app: my-backend
        type: backend
#        matchLabels:
#            type: frontend
